# Generated by Django 4.0.3 on 2022-04-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
